spring:
  datasource:
    url: jdbc:mysql://yuti-db-server.cfgygnwgvupa.ap-northeast-2.rds.amazonaws.com:3306/yuti
    username: yuti_admin
    password: dbxldjemalsqlalfqjsghdlqslek
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace
  #server.port=9090