es:
  host: j7a502.p.ssafy.io
  id: elastic
  password: dbxldjemalsqlalfqjsghdlqslek
  search-index: youtuber-analyzer
  result-index: mbti-result

youtube:
  keys: AIzaSyCRKFIDFHYH2741S67UQUIw14rohBi2NwU,AIzaSyCRKFIDFHYH2741S67UQUIw14rohBi2NwU,AIzaSyCRKFIDFHYH2741S67UQUIw14rohBi2NwU,AIzaSyCRKFIDFHYH2741S67UQUIw14rohBi2NwU,AIzaSyCRKFIDFHYH2741S67UQUIw14rohBi2NwU

spring:
  kafka:
    bootstrap-servers: j7a502.p.ssafy.io:9092
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
