es:
  host: j7a502.p.ssafy.io:9200
  search-index: youtuber-analyzer
  result-index: mbti-result

youtube:
  key: AIzaSyBfd5es8yHwOVnuARf3ehWizJc6hgf1e0c

spring:
  kafka:
    bootstrap-servers: j7a502.p.ssafy.io:9092
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
